# KT Note2 S Pen: five-point physical calibration, 2026-09-19.
# Keep the finger touchscreen's coordinates unchanged.
input "1386:0:Wacom_T0_Note2_S_Pen" {
    map_to_output DSI-1
    map_from_region 0.086317804x0.082793645 0.913226467x0.960712215
}
