# Linux evdev codes + 8: KEY_MENU=139, KEY_BACK=158, KEY_OK=352.
bindcode --release --input-device=0:0:tm2-touchkey 147 exec /usr/local/bin/note2-sxmo-keys menu
bindcode --release --input-device=0:0:tm2-touchkey 166 exec /usr/local/bin/note2-sxmo-keys close
bindcode --release --input-device=1:1:gpio-keys 360 exec /usr/local/bin/note2-sxmo-keys home

# Sxmo temporarily changes binding mode while menus are open.
mode "menu" {
    bindcode --release --input-device=0:0:tm2-touchkey 147 exec /usr/local/bin/note2-sxmo-keys menu
    bindcode --release --input-device=0:0:tm2-touchkey 166 exec /usr/local/bin/note2-sxmo-keys close
    bindcode --release --input-device=1:1:gpio-keys 360 exec /usr/local/bin/note2-sxmo-keys home
}
